<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Agent|Agents' => '',
  'Birthday Date' => '',
  'Birthday Place' => '',
  'DeliveryReport|DeliveryReports' => '',
  'Email' => '',
  'Failed Logins' => '',
  'Home' => '',
  'ID' => '',
  'Icc' => '',
  'Icq' => '',
  'Middle Name' => '',
  'Name' => '',
  'Number' => '',
  'Number Price' => '',
  'Operator' => '',
  'Operator|Operators' => '',
  'Passport Issue Date' => '',
  'Passport Issuer' => '',
  'Passport Number' => '',
  'Passport Series' => '',
  'Personal Account' => '',
  'Phone1' => '',
  'Phone2' => '',
  'Phone3' => '',
  'Price Agent Sim' => '',
  'Price License Fee' => '',
  'Registration Place' => '',
  'Sim|Sims' => '',
  'Skype' => '',
  'State' => '',
  'Status' => '',
  'Surname' => '',
  'Tariff|Tariffs' => '',
  'Title' => '',
  'User with this username already exists' => '',
  'Active' => 'Активен',
  'Blocked' => 'Заблокирован',
  'Blocked Until' => 'Заблокирован До',
  'Enter' => 'Войти',
  'Invalid username/password' => 'Неправильное имя пользователя и/или пароль',
  'Logout' => 'Выйти',
  'Password' => 'Пароль',
  'Please login' => 'Пожалуйста авторизуйтесь',
  'Remember me' => 'Запомнить меня',
  'Username' => 'Имя пользователя',
  'User|Users' => 'Пользователь|Пользователи',
  'Your account blocked by admin' => 'Ваш аккаунт заблокирован администратором',
  'Your account blocked for :m minutes due to invalid logins.' => 'Ваш аккаунт заблокирован на :m минут из-за неуспешных попыток авторизации',
);
