<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Agent' => 'Агент',
  'Authorization data' => 'Авторизационные данные',
  'Can\'t create directory %dir%' => '',
  'Can\'t find uploaded file info' => '',
  'Can\'t move file from %from% to %to%' => '',
  'DeliveryReport|DeliveryReports' => '',
  'Email' => '',
  'Failed Logins' => '',
  'File uploaded with error %error%' => '',
  'Home' => '',
  'ID' => '',
  'No File yet uploaded' => '',
  'No Image yet uploaded' => '',
  'Number' => '',
  'Number Price' => '',
  'Operator' => '',
  'Operator|Operators' => '',
  'Passport' => 'Паспорт',
  'Payment|Payments' => '',
  'Personal Account' => '',
  'Price Agent Sim' => '',
  'Price License Fee' => '',
  'Sim|Sims' => '',
  'Skype' => '',
  'State' => '',
  'Status' => '',
  'Summ' => '',
  'Tariff|Tariffs' => '',
  'Title' => '',
  'Your request is invalid.' => '',
  'Active' => 'Активен',
  'Agents' => 'Агенты',
  'Agent|Agents' => 'Агент|Агенты',
  'Are you sure to delete this Agent?' => 'Вы действительно хотите удалить этого агента?',
  'Balance' => 'Баланс',
  'Birthday Date' => 'Дата рождения',
  'Birthday Place' => 'Место рождения',
  'Blocked' => 'Заблокирован',
  'Blocked Until' => 'Заблокирован До',
  'Can\'t delete this object because it is used by another object(s)' => 'Не могу удалить данный объект, т.к. он используется',
  'Cancel' => 'Отменить',
  'Create' => 'Добавить',
  'Creating Agent' => 'Добавление агента',
  'Dt' => 'Дата',
  'Enter' => 'Войти',
  'Fields with' => 'Поля, отмеченные',
  'Icc' => 'ICC',
  'Icq' => 'ICQ',
  'Invalid username/password' => 'Неправильное имя пользователя и/или пароль',
  'List' => 'Список',
  'Logout' => 'Выйти',
  'Middle Name' => 'Отчество',
  'Name' => 'Имя',
  'Passport Issue Date' => 'Дата выдачи',
  'Passport Issuer' => 'Кем выдан',
  'Passport Number' => 'Номер',
  'Passport Series' => 'Серия',
  'Password' => 'Пароль',
  'Phone 1' => 'Телефон 1',
  'Phone 2' => 'Телефон 2',
  'Phone 3' => 'Телефон 3',
  'Please login' => 'Пожалуйста авторизуйтесь',
  'Registration Address' => 'Адрес регистрации',
  'Remember me' => 'Запомнить меня',
  'Save' => 'Сохранение',
  'Surname' => 'Фамилия',
  'Updating Agent' => 'Редактирование агента',
  'User with this username already exists' => 'Пользователь с данным именем уже существует',
  'Username' => 'Имя пользователя',
  'User|Users' => 'Пользователь|Пользователи',
  'Your account blocked by admin' => 'Ваш аккаунт заблокирован администратором',
  'Your account blocked for :m minutes due to invalid logins.' => 'Ваш аккаунт заблокирован на :m минут из-за неуспешных попыток авторизации',
  'are required' => 'обязательны для заполнения',

  'MenuSim' => 'Сим карты',
  'addDeliveryReport' => 'Загрузка накладной',
  'addSim' => 'Добавление сим карт',
  'buttonAddSim'=>'Добавить симкарты',
  'buttonProcessSim' => 'Обработать',
);
