<?php

/**
 * This is the model base class for the table "tariff".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tariff".
 *
 * Columns in table "tariff" available as properties of the model,
 * followed by relations of table "tariff" available as properties of the model.
 *
 * @property string $id
 * @property string $operator_id
 * @property string $title
 * @property double $price_agent_sim
 * @property double $price_license_fee
 *
 * @property Sim[] $sims
 * @property Operator $operator
 */
abstract class BaseTariff extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tariff';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tariff|Tariffs', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('operator_id, title, price_agent_sim, price_license_fee', 'required'),
			array('price_agent_sim, price_license_fee', 'numerical'),
			array('operator_id', 'length', 'max'=>20),
			array('title', 'length', 'max'=>50),
			array('id, operator_id, title, price_agent_sim, price_license_fee', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sims' => array(self::HAS_MANY, 'Sim', 'tariff_id'),
			'operator' => array(self::BELONGS_TO, 'Operator', 'operator_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'operator_id' => null,
			'title' => Yii::t('app', 'Title'),
			'price_agent_sim' => Yii::t('app', 'Price Agent Sim'),
			'price_license_fee' => Yii::t('app', 'Price License Fee'),
			'sims' => null,
			'operator' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('operator_id', $this->operator_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('price_agent_sim', $this->price_agent_sim);
		$criteria->compare('price_license_fee', $this->price_license_fee);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}