<?php

/**
 * This is the model base class for the table "balance_report_number".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BalanceReportNumber".
 *
 * Columns in table "balance_report_number" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $balance_report_id
 * @property string $number_id
 * @property string $balance
 *
 */
abstract class BaseBalanceReportNumber extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'balance_report_number';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BalanceReportNumber|BalanceReportNumbers', $n);
	}

	public static function representingColumn() {
		return array(
			'balance_report_id',
			'number_id',
		);
	}

	public function rules() {
		return array(
			array('balance_report_id, number_id, balance', 'required'),
			array('balance_report_id', 'numerical', 'integerOnly'=>true),
			array('number_id', 'length', 'max'=>20),
			array('balance', 'length', 'max'=>14),
			array('balance_report_id, number_id, balance', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'balance_report_id' => null,
			'number_id' => null,
			'balance' => Yii::t('app', 'Balance'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('balance_report_id', $this->balance_report_id);
		$criteria->compare('number_id', $this->number_id);
		$criteria->compare('balance', $this->balance, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}