<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * followed by relations of table "user" available as properties of the model.
 *
 * @property string $id
 * @property string $status
 * @property string $username
 * @property string $password
 * @property integer $failed_logins
 * @property string $blocked_until
 *
 * @property Agent[] $agents
 */
abstract class BaseUser extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'status';
	}

	public function rules() {
		return array(
			array('status, username', 'required'),
			array('failed_logins', 'numerical', 'integerOnly'=>true),
			array('status', 'length', 'max'=>7),
			array('username, password', 'length', 'max'=>200),
			array('blocked_until', 'safe'),
			array('password, failed_logins, blocked_until', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, status, username, password, failed_logins, blocked_until', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agents' => array(self::HAS_MANY, 'Agent', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'status' => Yii::t('app', 'Status'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'failed_logins' => Yii::t('app', 'Failed Logins'),
			'blocked_until' => Yii::t('app', 'Blocked Until'),
			'agents' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('failed_logins', $this->failed_logins);
		$criteria->compare('blocked_until', $this->blocked_until, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}