<?php

/**
 * This is the model base class for the table "cashier_collection".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CashierCollection".
 *
 * Columns in table "cashier_collection" available as properties of the model,
 * followed by relations of table "cashier_collection" available as properties of the model.
 *
 * @property integer $id
 * @property string $dt
 * @property integer $cashier_support_operator_id
 * @property integer $collector_support_operator_id
 * @property string $sum
 *
 * @property SupportOperator $cashierSupportOperator
 * @property SupportOperator $collectorSupportOperator
 */
abstract class BaseCashierCollection extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cashier_collection';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CashierCollection|CashierCollections', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('dt, cashier_support_operator_id, collector_support_operator_id, sum', 'required'),
			array('cashier_support_operator_id, collector_support_operator_id', 'numerical', 'integerOnly'=>true),
			array('sum', 'length', 'max'=>14),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, dt, cashier_support_operator_id, collector_support_operator_id, sum', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cashierSupportOperator' => array(self::BELONGS_TO, 'SupportOperator', 'cashier_support_operator_id'),
			'collectorSupportOperator' => array(self::BELONGS_TO, 'SupportOperator', 'collector_support_operator_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'dt' => Yii::t('app', 'Dt'),
			'cashier_support_operator_id' => null,
			'collector_support_operator_id' => null,
			'sum' => Yii::t('app', 'Sum'),
			'cashierSupportOperator' => null,
			'collectorSupportOperator' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('cashier_support_operator_id', $this->cashier_support_operator_id);
		$criteria->compare('collector_support_operator_id', $this->collector_support_operator_id);
		$criteria->compare('sum', $this->sum, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}