<?php

/**
 * This is the model base class for the table "subscription_agreement".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SubscriptionAgreement".
 *
 * Columns in table "subscription_agreement" available as properties of the model,
 * followed by relations of table "subscription_agreement" available as properties of the model.
 *
 * @property string $id
 * @property string $defined_id
 * @property string $dt
 * @property string $number_id
 * @property string $person_id
 *
 * @property Number $number
 * @property Person $person
 * @property File[] $files
 */
abstract class BaseSubscriptionAgreement extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'subscription_agreement';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SubscriptionAgreement|SubscriptionAgreements', $n);
	}

	public static function representingColumn() {
		return 'defined_id';
	}

	public function rules() {
		return array(
			array('defined_id', 'length', 'max'=>50),
			array('number_id, person_id', 'length', 'max'=>20),
			array('dt', 'safe'),
			array('defined_id, dt, number_id, person_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, defined_id, dt, number_id, person_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'number' => array(self::BELONGS_TO, 'Number', 'number_id'),
			'person' => array(self::BELONGS_TO, 'Person', 'person_id'),
			'files' => array(self::MANY_MANY, 'File', 'subscription_agreement_file(subscription_agreement_id, file_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'files' => 'SubscriptionAgreementFile',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'defined_id' => Yii::t('app', 'Defined'),
			'dt' => Yii::t('app', 'Dt'),
			'number_id' => null,
			'person_id' => null,
			'number' => null,
			'person' => null,
			'files' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('defined_id', $this->defined_id, true);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('number_id', $this->number_id);
		$criteria->compare('person_id', $this->person_id);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}