<?php

/**
 * This is the model base class for the table "file".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "File".
 *
 * Columns in table "file" available as properties of the model,
 * followed by relations of table "file" available as properties of the model.
 *
 * @property string $id
 * @property string $url
 *
 * @property Person[] $people
 * @property SubscriptionAgreement[] $subscriptionAgreements
 */
abstract class BaseFile extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'file';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'File|Files', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('url', 'required'),
			array('url', 'length', 'max'=>200),
			array('id, url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'people' => array(self::MANY_MANY, 'Person', 'person_file(file_id, person_id)'),
			'subscriptionAgreements' => array(self::MANY_MANY, 'SubscriptionAgreement', 'subscription_agreement_file(file_id, subscription_agreement_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'people' => 'PersonFile',
			'subscriptionAgreements' => 'SubscriptionAgreementFile',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'url' => Yii::t('app', 'Url'),
			'people' => null,
			'subscriptionAgreements' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('url', $this->url, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}