<?php

/**
 * This is the model base class for the table "delivery_report".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DeliveryReport".
 *
 * Columns in table "delivery_report" available as properties of the model,
 * followed by relations of table "delivery_report" available as properties of the model.
 *
 * @property string $id
 * @property string $agent_id
 * @property string $dt
 * @property double $sim_price
 * @property double $summ
 *
 * @property Agent $agent
 * @property Sim[] $sims
 */
abstract class BaseDeliveryReport extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'delivery_report';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DeliveryReport|DeliveryReports', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('agent_id, dt, sim_price, summ', 'required'),
			array('sim_price, summ', 'numerical'),
			array('agent_id', 'length', 'max'=>20),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, agent_id, dt, sim_price, summ', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agent' => array(self::BELONGS_TO, 'Agent', 'agent_id'),
			'sims' => array(self::HAS_MANY, 'Sim', 'delivery_report_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'agent_id' => null,
			'dt' => Yii::t('app', 'Dt'),
			'sim_price' => Yii::t('app', 'Sim Price'),
			'summ' => Yii::t('app', 'Summ'),
			'agent' => null,
			'sims' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('sim_price', $this->sim_price);
		$criteria->compare('summ', $this->summ);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($column,$val) {
        if (is_string($val)) {
            if ($column=='dt') $val=$this->convertStringToEDateTime($val,'datetime');
        }
        parent::setAttribute($column,$val);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}