<?php

/**
 * This is the model base class for the table "ticket".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ticket".
 *
 * Columns in table "ticket" available as properties of the model,
 * followed by relations of table "ticket" available as properties of the model.
 *
 * @property string $id
 * @property string $number_id
 * @property string $sim_id
 * @property integer $agent_id
 * @property integer $support_operator_id
 * @property string $dt
 * @property string $status
 * @property string $text
 * @property string $internal
 * @property string $response
 *
 * @property Number $number
 * @property Sim $sim
 * @property Agent $agent
 * @property SupportOperator $supportOperator
 * @property TicketHistory[] $ticketHistories
 */
abstract class BaseTicket extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ticket';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ticket|Tickets', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('number_id, sim_id, agent_id, dt, status, text', 'required'),
			array('agent_id, support_operator_id', 'numerical', 'integerOnly'=>true),
			array('number_id, sim_id', 'length', 'max'=>20),
			array('status', 'length', 'max'=>19),
			array('internal, response', 'safe'),
			array('support_operator_id, internal, response', 'default', 'setOnEmpty' => true, 'value' => null),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, number_id, sim_id, agent_id, support_operator_id, dt, status, text, internal, response', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'number' => array(self::BELONGS_TO, 'Number', 'number_id'),
			'sim' => array(self::BELONGS_TO, 'Sim', 'sim_id'),
			'agent' => array(self::BELONGS_TO, 'Agent', 'agent_id'),
			'supportOperator' => array(self::BELONGS_TO, 'SupportOperator', 'support_operator_id'),
			'ticketHistories' => array(self::HAS_MANY, 'TicketHistory', 'ticket_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'number_id' => null,
			'sim_id' => null,
			'agent_id' => null,
			'support_operator_id' => null,
			'dt' => Yii::t('app', 'Dt'),
			'status' => Yii::t('app', 'Status'),
			'text' => Yii::t('app', 'Text'),
			'internal' => Yii::t('app', 'Internal'),
			'response' => Yii::t('app', 'Response'),
			'number' => null,
			'sim' => null,
			'agent' => null,
			'supportOperator' => null,
			'ticketHistories' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('number_id', $this->number_id);
		$criteria->compare('sim_id', $this->sim_id);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('support_operator_id', $this->support_operator_id);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('internal', $this->internal, true);
		$criteria->compare('response', $this->response, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}