<?php

/**
 * This is the model base class for the table "sms_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SmsLog".
 *
 * Columns in table "sms_log" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $user_id
 * @property string $number
 * @property string $text
 * @property string $dt
 *
 */
abstract class BaseSmsLog extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sms_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SmsLog|SmsLogs', $n);
	}

	public static function representingColumn() {
		return 'number';
	}

	public function rules() {
		return array(
			array('user_id, number, text, dt', 'required'),
			array('user_id', 'length', 'max'=>20),
			array('number', 'length', 'max'=>50),
			array('text', 'length', 'max'=>140),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, user_id, number, text, dt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'number' => Yii::t('app', 'Number'),
			'text' => Yii::t('app', 'Text'),
			'dt' => Yii::t('app', 'Dt'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('number', $this->number, true);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('dt', $this->dt, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}