<?php

/**
 * This is the model base class for the table "sim_delivery_report".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SimDeliveryReport".
 *
 * Columns in table "sim_delivery_report" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $sim_id
 * @property string $delivery_report_id
 *
 */
abstract class BaseSimDeliveryReport extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sim_delivery_report';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SimDeliveryReport|SimDeliveryReports', $n);
	}

	public static function representingColumn() {
		return array(
			'sim_id',
			'delivery_report_id',
		);
	}

	public function rules() {
		return array(
			array('sim_id, delivery_report_id', 'required'),
			array('sim_id, delivery_report_id', 'length', 'max'=>20),
			array('sim_id, delivery_report_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'sim_id' => null,
			'delivery_report_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('sim_id', $this->sim_id);
		$criteria->compare('delivery_report_id', $this->delivery_report_id);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}