<?php

/**
 * This is the model base class for the table "bonus_report_agent".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BonusReportAgent".
 *
 * Columns in table "bonus_report_agent" available as properties of the model,
 * followed by relations of table "bonus_report_agent" available as properties of the model.
 *
 * @property integer $id
 * @property integer $bonus_report_id
 * @property integer $agent_id
 * @property integer $sim_count
 * @property double $sum
 * @property double $sum_referrals
 * @property integer $payment_id
 *
 * @property BonusReport $bonusReport
 * @property Agent $agent
 * @property Payment $payment
 */
abstract class BaseBonusReportAgent extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'bonus_report_agent';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BonusReportAgent|BonusReportAgents', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('bonus_report_id, agent_id, sim_count, sum, sum_referrals, payment_id', 'required'),
			array('bonus_report_id, agent_id, sim_count, payment_id', 'numerical', 'integerOnly'=>true),
			array('sum, sum_referrals', 'numerical'),
			array('id, bonus_report_id, agent_id, sim_count, sum, sum_referrals, payment_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bonusReport' => array(self::BELONGS_TO, 'BonusReport', 'bonus_report_id'),
			'agent' => array(self::BELONGS_TO, 'Agent', 'agent_id'),
			'payment' => array(self::BELONGS_TO, 'Payment', 'payment_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bonus_report_id' => null,
			'agent_id' => null,
			'sim_count' => Yii::t('app', 'Sim Count'),
			'sum' => Yii::t('app', 'Sum'),
			'sum_referrals' => Yii::t('app', 'Sum Referrals'),
			'payment_id' => null,
			'bonusReport' => null,
			'agent' => null,
			'payment' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bonus_report_id', $this->bonus_report_id);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('sim_count', $this->sim_count);
		$criteria->compare('sum', $this->sum);
		$criteria->compare('sum_referrals', $this->sum_referrals);
		$criteria->compare('payment_id', $this->payment_id);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}