<?php

/**
 * This is the model base class for the table "ticket".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ticket".
 *
 * Columns in table "ticket" available as properties of the model,
 * followed by relations of table "ticket" available as properties of the model.
 *
 * @property integer $id
 * @property integer $agent_id
 * @property string $title
 * @property string $dt
 * @property integer $whom
 * @property string $status
 *
 * @property TicketMessage[] $ticketMessages
 */
abstract class BaseTicket extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ticket';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ticket|Tickets', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('agent_id, dt, whom', 'required'),
			array('agent_id, whom', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>256),
			array('status', 'length', 'max'=>6),
			array('title, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, agent_id, title, dt, whom, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ticketMessages' => array(self::HAS_MANY, 'TicketMessage', 'ticket_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'agent_id' => Yii::t('app', 'Agent'),
			'title' => Yii::t('app', 'Title'),
			'dt' => Yii::t('app', 'Dt'),
			'whom' => Yii::t('app', 'Whom'),
			'status' => Yii::t('app', 'Status'),
			'ticketMessages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('whom', $this->whom);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}