<?php

/**
 * This is the model base class for the table "sim_act".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SimAct".
 *
 * Columns in table "sim_act" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $sim_id
 * @property string $act_id
 *
 */
abstract class BaseSimAct extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sim_act';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SimAct|SimActs', $n);
	}

	public static function representingColumn() {
		return array(
			'sim_id',
			'act_id',
		);
	}

	public function rules() {
		return array(
			array('sim_id, act_id', 'required'),
			array('sim_id, act_id', 'length', 'max'=>20),
			array('sim_id, act_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'sim_id' => null,
			'act_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('sim_id', $this->sim_id);
		$criteria->compare('act_id', $this->act_id);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}