<?php

/**
 * This is the model base class for the table "operator_region".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OperatorRegion".
 *
 * Columns in table "operator_region" available as properties of the model,
 * followed by relations of table "operator_region" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property integer $operator_id
 *
 * @property Operator $operator
 * @property Sim[] $sims
 */
abstract class BaseOperatorRegion extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'operator_region';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OperatorRegion|OperatorRegions', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, operator_id', 'required'),
			array('operator_id', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>200),
			array('id, title, operator_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'operator' => array(self::BELONGS_TO, 'Operator', 'operator_id'),
			'sims' => array(self::HAS_MANY, 'Sim', 'operator_region_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'operator_id' => null,
			'operator' => null,
			'sims' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('operator_id', $this->operator_id);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}