<?php

/**
 * This is the model base class for the table "megafon_app_restore".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MegafonAppRestore".
 *
 * Columns in table "megafon_app_restore" available as properties of the model,
 * followed by relations of table "megafon_app_restore" available as properties of the model.
 *
 * @property integer $id
 * @property string $dt
 * @property integer $numbers_count
 * @property integer $unprocessed_numbers_count
 * @property integer $sent_to_email
 *
 * @property MegafonAppRestoreNumber[] $megafonAppRestoreNumbers
 */
abstract class BaseMegafonAppRestore extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'megafon_app_restore';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MegafonAppRestore|MegafonAppRestores', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('dt', 'required'),
			array('numbers_count, unprocessed_numbers_count, sent_to_email', 'numerical', 'integerOnly'=>true),
			array('numbers_count, unprocessed_numbers_count, sent_to_email', 'default', 'setOnEmpty' => true, 'value' => null),
            array('dt','date','format'=>'dd.MM.yyyy'),
			array('id, dt, numbers_count, unprocessed_numbers_count, sent_to_email', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'megafonAppRestoreNumbers' => array(self::HAS_MANY, 'MegafonAppRestoreNumber', 'megafon_app_restore_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'dt' => Yii::t('app', 'Dt'),
			'numbers_count' => Yii::t('app', 'Numbers Count'),
			'unprocessed_numbers_count' => Yii::t('app', 'Unprocessed Numbers Count'),
			'sent_to_email' => Yii::t('app', 'Sent To Email'),
			'megafonAppRestoreNumbers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('numbers_count', $this->numbers_count);
		$criteria->compare('unprocessed_numbers_count', $this->unprocessed_numbers_count);
		$criteria->compare('sent_to_email', $this->sent_to_email);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'date');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}