<?php

/**
 * This is the model base class for the table "ticket_message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TicketMessage".
 *
 * Columns in table "ticket_message" available as properties of the model,
 * followed by relations of table "ticket_message" available as properties of the model.
 *
 * @property integer $id
 * @property integer $ticket_id
 * @property integer $agent_id
 * @property string $message
 * @property string $dt
 *
 * @property Ticket $ticket
 */
abstract class BaseTicketMessage extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ticket_message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TicketMessage|TicketMessages', $n);
	}

	public static function representingColumn() {
		return 'message';
	}

	public function rules() {
		return array(
			array('ticket_id, agent_id, message, dt', 'required'),
			array('ticket_id, agent_id', 'numerical', 'integerOnly'=>true),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, ticket_id, agent_id, message, dt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ticket' => array(self::BELONGS_TO, 'Ticket', 'ticket_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ticket_id' => null,
			'agent_id' => Yii::t('app', 'Agent'),
			'message' => Yii::t('app', 'Message'),
			'dt' => Yii::t('app', 'Dt'),
			'ticket' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ticket_id', $this->ticket_id);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('dt', $this->dt, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}