<?php

/**
 * This is the model base class for the table "ticket".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ticket".
 *
 * Columns in table "ticket" available as properties of the model,
 * followed by relations of table "ticket" available as properties of the model.
 *
 * @property integer $id
 * @property integer $agent_id
 * @property string $title
 * @property string $dt
 * @property integer $whom
 * @property string $status
 * @property double $prise
 *
 * @property Agent $agent
 * @property TicketMessage[] $ticketMessages
 */
abstract class BaseTicket extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ticket';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ticket|Tickets', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('agent_id, dt, whom', 'required'),
			array('agent_id, whom', 'numerical', 'integerOnly'=>true),
			array('prise', 'numerical'),
			array('title', 'length', 'max'=>256),
			array('status', 'length', 'max'=>6),
			array('title, status, prise', 'default', 'setOnEmpty' => true, 'value' => null),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, agent_id, title, dt, whom, status, prise', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agent' => array(self::BELONGS_TO, 'Agent', 'agent_id'),
			'ticketMessages' => array(self::HAS_MANY, 'TicketMessage', 'ticket_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'agent_id' => null,
			'title' => Yii::t('app', 'Title'),
			'dt' => Yii::t('app', 'Dt'),
			'whom' => Yii::t('app', 'Whom'),
			'status' => Yii::t('app', 'Status'),
			'prise' => Yii::t('app', 'Prise'),
			'agent' => null,
			'ticketMessages' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('whom', $this->whom);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('prise', $this->prise);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}