<?php

/**
 * This is the model base class for the table "ticket_message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TicketMessage".
 *
 * Columns in table "ticket_message" available as properties of the model,
 * followed by relations of table "ticket_message" available as properties of the model.
 *
 * @property integer $id
 * @property integer $ticket_id
 * @property integer $agent_id
 * @property string $message
 * @property string $date
 *
 * @property Ticket $ticket
 */
abstract class BaseTicketMessage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ticket_message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TicketMessage|TicketMessages', $n);
	}

	public static function representingColumn() {
		return 'message';
	}

	public function rules() {
		return array(
			array('ticket_id, agent_id, message, date', 'required'),
			array('ticket_id, agent_id', 'numerical', 'integerOnly'=>true),
			array('id, ticket_id, agent_id, message, date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ticket' => array(self::BELONGS_TO, 'Ticket', 'ticket_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ticket_id' => null,
			'agent_id' => Yii::t('app', 'Agent'),
			'message' => Yii::t('app', 'Message'),
			'date' => Yii::t('app', 'Date'),
			'ticket' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ticket_id', $this->ticket_id);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('message', $this->message, true);
		$criteria->compare('date', $this->date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}