<?php

/**
 * This is the model base class for the table "number_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NumberHistory".
 *
 * Columns in table "number_history" available as properties of the model,
 * followed by relations of table "number_history" available as properties of the model.
 *
 * @property integer $id
 * @property string $number_id
 * @property string $dt
 * @property string $who
 * @property string $comment
 *
 * @property Number $number
 */
abstract class BaseNumberHistory extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'number_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NumberHistory|NumberHistories', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('number_id, dt, who, comment', 'required'),
			array('number_id', 'length', 'max'=>20),
			array('who, comment', 'length', 'max'=>200),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, number_id, dt, who, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'number' => array(self::BELONGS_TO, 'Number', 'number_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'number_id' => null,
			'dt' => Yii::t('app', 'Dt'),
			'who' => Yii::t('app', 'Who'),
			'comment' => Yii::t('app', 'Comment'),
			'number' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('number_id', $this->number_id);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('who', $this->who, true);
		$criteria->compare('comment', $this->comment, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}