<?php

/**
 * This is the model base class for the table "ticket_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TicketHistory".
 *
 * Columns in table "ticket_history" available as properties of the model,
 * followed by relations of table "ticket_history" available as properties of the model.
 *
 * @property string $id
 * @property string $ticket_id
 * @property string $dt
 * @property integer $support_operator_id
 * @property string $comment
 * @property string $status
 *
 * @property Ticket $ticket
 * @property SupportOperator $supportOperator
 */
abstract class BaseTicketHistory extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ticket_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TicketHistory|TicketHistories', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('ticket_id, dt, support_operator_id, status', 'required'),
			array('support_operator_id', 'numerical', 'integerOnly'=>true),
			array('ticket_id', 'length', 'max'=>20),
			array('status', 'length', 'max'=>19),
			array('comment', 'safe'),
			array('comment', 'default', 'setOnEmpty' => true, 'value' => null),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, ticket_id, dt, support_operator_id, comment, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ticket' => array(self::BELONGS_TO, 'Ticket', 'ticket_id'),
			'supportOperator' => array(self::BELONGS_TO, 'SupportOperator', 'support_operator_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ticket_id' => null,
			'dt' => Yii::t('app', 'Dt'),
			'support_operator_id' => null,
			'comment' => Yii::t('app', 'Comment'),
			'status' => Yii::t('app', 'Status'),
			'ticket' => null,
			'supportOperator' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('ticket_id', $this->ticket_id);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('support_operator_id', $this->support_operator_id);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('status', $this->status, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}