<?php

/**
 * This is the model base class for the table "delivery_report".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DeliveryReport".
 *
 * Columns in table "delivery_report" available as properties of the model,
 * followed by relations of table "delivery_report" available as properties of the model.
 *
 * @property integer $id
 * @property integer $parent_agent_id
 * @property integer $agent_id
 * @property string $dt
 * @property double $sim_price
 * @property double $sum
 *
 * @property Agent $agent
 * @property Agent $parentAgent
 * @property Sim[] $sims
 * @property Sim[] $sims1
 */
abstract class BaseDeliveryReport extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'delivery_report';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DeliveryReport|DeliveryReports', $n);
	}

	public static function representingColumn() {
		return 'dt';
	}

	public function rules() {
		return array(
			array('agent_id, dt, sim_price, sum', 'required'),
			array('parent_agent_id, agent_id', 'numerical', 'integerOnly'=>true),
			array('sim_price, sum', 'numerical'),
			array('parent_agent_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, parent_agent_id, agent_id, dt, sim_price, sum', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agent' => array(self::BELONGS_TO, 'Agent', 'agent_id'),
			'parentAgent' => array(self::BELONGS_TO, 'Agent', 'parent_agent_id'),
			'sims' => array(self::HAS_MANY, 'Sim', 'delivery_report_id'),
			'sims1' => array(self::HAS_MANY, 'Sim', 'parent_delivery_report_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'parent_agent_id' => null,
			'agent_id' => null,
			'dt' => Yii::t('app', 'Dt'),
			'sim_price' => Yii::t('app', 'Sim Price'),
			'sum' => Yii::t('app', 'Sum'),
			'agent' => null,
			'parentAgent' => null,
			'sims' => null,
			'sims1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('parent_agent_id', $this->parent_agent_id);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('sim_price', $this->sim_price);
		$criteria->compare('sum', $this->sum);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}