<?php

/**
 * This is the model base class for the table "payment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Payment".
 *
 * Columns in table "payment" available as properties of the model,
 * followed by relations of table "payment" available as properties of the model.
 *
 * @property integer $id
 * @property integer $agent_id
 * @property string $type
 * @property string $comment
 * @property string $dt
 * @property double $sum
 *
 * @property Agent $agent
 */
abstract class BasePayment extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'payment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Payment|Payments', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('agent_id, type, dt, sum', 'required'),
			array('agent_id', 'numerical', 'integerOnly'=>true),
			array('sum', 'numerical'),
			array('type', 'length', 'max'=>6),
			array('comment', 'length', 'max'=>200),
			array('comment', 'default', 'setOnEmpty' => true, 'value' => null),
            array('dt','date','format'=>'dd.MM.yyyy HH:mm:ss'),
			array('id, agent_id, type, comment, dt, sum', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agent' => array(self::BELONGS_TO, 'Agent', 'agent_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'agent_id' => null,
			'type' => Yii::t('app', 'Type'),
			'comment' => Yii::t('app', 'Comment'),
			'dt' => Yii::t('app', 'Dt'),
			'sum' => Yii::t('app', 'Sum'),
			'agent' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('dt', $this->dt, true);
		$criteria->compare('sum', $this->sum);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

    public function convertDateTimeFieldsToEDateTime() {
        // rest of work will do setAttribute() routine
        $this->setAttribute('dt',strval($this->dt));
    }

    public function convertDateTimeFieldsToString() {
        if (is_object($this->dt) && get_class($this->dt)=='EDateTime') $this->dt=new EString($this->dt->format(self::$mySqlDateTimeFormat));
    }

    public function afterFind() {
        $this->convertDateTimeFieldsToEDateTime();
    }

    private function convertStringToEDateTime($val,$type) {
        if (!$val) return null;
        try {
            $val=new EDateTime($val,null,$type);
        } catch (Exception $e) {
        }
        return $val;
    }

    public function setAttribute($name,$value) {
        if (is_string($value)) {
            if ($name=='dt') $value=$this->convertStringToEDateTime($value,'datetime');
        }
        return parent::setAttribute($name,$value);
    }

    public function beforeSave() {
        $this->convertDateTimeFieldsToString();

        return true;
    }

    public function afterSave() {
        $this->convertDateTimeFieldsToEDateTime();
    }
}