<?php

/**
 * This is the model base class for the table "megafon_app_restore_number".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MegafonAppRestoreNumber".
 *
 * Columns in table "megafon_app_restore_number" available as properties of the model,
 * followed by relations of table "megafon_app_restore_number" available as properties of the model.
 *
 * @property string $id
 * @property integer $megafon_app_restore_id
 * @property string $number_id
 * @property integer $support_operator_id
 * @property string $sim_type
 * @property string $status
 * @property string $cashier_debit_credit_id
 * @property string $contact_phone
 * @property string $contact_name
 *
 * @property CashierDebitCredit $cashierDebitCredit
 * @property Number $number
 * @property MegafonAppRestore $megafonAppRestore
 * @property SupportOperator $supportOperator
 */
abstract class BaseMegafonAppRestoreNumber extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'megafon_app_restore_number';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MegafonAppRestoreNumber|MegafonAppRestoreNumbers', $n);
	}

	public static function representingColumn() {
		return 'sim_type';
	}

	public function rules() {
		return array(
			array('megafon_app_restore_id, number_id, sim_type, status', 'required'),
			array('megafon_app_restore_id, support_operator_id', 'numerical', 'integerOnly'=>true),
			array('number_id, cashier_debit_credit_id, contact_phone', 'length', 'max'=>20),
			array('sim_type', 'length', 'max'=>6),
			array('status', 'length', 'max'=>10),
			array('contact_name', 'length', 'max'=>100),
			array('support_operator_id, cashier_debit_credit_id, contact_phone, contact_name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, megafon_app_restore_id, number_id, support_operator_id, sim_type, status, cashier_debit_credit_id, contact_phone, contact_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cashierDebitCredit' => array(self::BELONGS_TO, 'CashierDebitCredit', 'cashier_debit_credit_id'),
			'number' => array(self::BELONGS_TO, 'Number', 'number_id'),
			'megafonAppRestore' => array(self::BELONGS_TO, 'MegafonAppRestore', 'megafon_app_restore_id'),
			'supportOperator' => array(self::BELONGS_TO, 'SupportOperator', 'support_operator_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'megafon_app_restore_id' => null,
			'number_id' => null,
			'support_operator_id' => null,
			'sim_type' => Yii::t('app', 'Sim Type'),
			'status' => Yii::t('app', 'Status'),
			'cashier_debit_credit_id' => null,
			'contact_phone' => Yii::t('app', 'Contact Phone'),
			'contact_name' => Yii::t('app', 'Contact Name'),
			'cashierDebitCredit' => null,
			'number' => null,
			'megafonAppRestore' => null,
			'supportOperator' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('megafon_app_restore_id', $this->megafon_app_restore_id);
		$criteria->compare('number_id', $this->number_id);
		$criteria->compare('support_operator_id', $this->support_operator_id);
		$criteria->compare('sim_type', $this->sim_type, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('cashier_debit_credit_id', $this->cashier_debit_credit_id);
		$criteria->compare('contact_phone', $this->contact_phone, true);
		$criteria->compare('contact_name', $this->contact_name, true);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}