<?php

/**
 * This is the model base class for the table "payment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Payment".
 *
 * Columns in table "payment" available as properties of the model,
 * followed by relations of table "payment" available as properties of the model.
 *
 * @property string $id
 * @property string $agent_id
 * @property double $summ
 *
 * @property Agent $agent
 */
abstract class BasePayment extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'payment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Payment|Payments', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('agent_id, summ', 'required'),
			array('summ', 'numerical'),
			array('agent_id', 'length', 'max'=>20),
			array('id, agent_id, summ', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'agent' => array(self::BELONGS_TO, 'Agent', 'agent_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'agent_id' => null,
			'summ' => Yii::t('app', 'Summ'),
			'agent' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('agent_id', $this->agent_id);
		$criteria->compare('summ', $this->summ);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}