<?php

/**
 * This is the model base class for the table "person_file".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonFile".
 *
 * Columns in table "person_file" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $person_id
 * @property string $file_id
 *
 */
abstract class BasePersonFile extends BaseGxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'person_file';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonFile|PersonFiles', $n);
	}

	public static function representingColumn() {
		return array(
			'person_id',
			'file_id',
		);
	}

	public function rules() {
		return array(
			array('person_id, file_id', 'required'),
			array('person_id, file_id', 'length', 'max'=>20),
			array('person_id, file_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'person_id' => null,
			'file_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('person_id', $this->person_id);
		$criteria->compare('file_id', $this->file_id);

		$dataProvider=new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));

        $dataProvider->pagination->pageSize=self::ITEMS_PER_PAGE;
        return $dataProvider;
	}

}